services:
  zfdash:
    privileged: false
    cap_add:
      - SYS_ADMIN
    security_opt:
      - seccomp=unconfined
    volumes:
      - /dev:/dev
      - /etc:/host-etc:ro  # Read-only access to check host's /etc/hostid
